### ISSUE TITLE
Auto Play

### ISSUE THREAD

**Issue by Lunatixz** [bradyemerson/plugin.video.pftv#1]
Can you add an option to auto play the sources instead of listing all the sources in each media directory? This makes parsing your plugin easier... BTW Great work!

**Comment by bradyemerson** [comment]
I'll have to experiment with this down the road. As you've probably discovered, many links die over time, so an autoplay would need to continue down the list until a valid link is found.

Also, many links require captchas before it is known if they are dead or not, which complicates things.

**Comment by Lunatixz** [comment]
ahhh do they, yeah captchas are my plugins enemy, lol... Nevermind then, keep up the great work :)

**Comment by Lunatixz** [comment]
You might want to consider not forcing video source folders, not everyone wants your folders as a source. Thanks

**Comment by bradyemerson** [comment]
You can change the export folder in the addon settings.  Although for now the plugin is using python native file handlers, not xbmcvfs, so only local paths are supported.  It's on my todo to change it to xbmcvfs
